apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik-worker
  template:
    metadata:
      labels:
        app: authentik-worker
    spec:
      containers:
        - name: authentik
          image: ghcr.io/goauthentik/server:2025.2.4
          command: ["ak"]
          args: ["worker"]
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: AUTHENTIK_SECRET_KEY

            - name: AUTHENTIK_POSTGRESQL__HOST
              value: postgres
            - name: AUTHENTIK_POSTGRESQL__USER
              value: authentik
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: POSTGRES_PASSWORD
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: authentik

            - name: AUTHENTIK_REDIS__HOST
              value: redis
