apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik
  namespace: authentik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik
  template:
    metadata:
      labels:
        app: authentik
    spec:
      containers:
        - name: authentik
          image: ghcr.io/goauthentik/server:latest
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: AUTHENTIK_SECRET_KEY

            - name: AUTHENTIK_POSTGRESQL__HOST
              value: postgres

            - name: AUTHENTIK_POSTGRESQL__USER
              value: authentik

            - name: AUTHENTIK_POSTGRESQL__NAME
              value: authentik

            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: POSTGRES_PASSWORD

            - name: AUTHENTIK_REDIS__HOST
              value: redis

