apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
type: Opaque
stringData:
  POSTGRES_PASSWORD: $Saikumar123$
  AUTHENTIK_SECRET_KEY: $Skystonesoftsolutionspvtltd268812$
